### ISSUE TITLE
Portspoof is running but nmap -F -sV 127.0.0.1 works

### ISSUE THREAD

**Issue by Belval** [drk1wi/portspoof#26]
Clean pull from master
OS: Ubuntu 16.04

    ./configure
    make
    sudo make install
    sudo portspoof -c /usr/local/etc/portspoof.conf -s /usr/local/etc/portspoof_signatures -D1

When I run nmap I see the process in `htop` but `nmap -F -sV 127.0.0.1` doesn't show any spoofed port.

**Comment by alasdairdc** [comment]
Have you tried it on the external IP address instead of the loopback IP?

**Comment by Belval** [comment]
I have not, but the doc seemed to imply that it would work.

**Comment by alasdairdc** [comment]
Its been ages since I looked at this but the [IPtables config](https://github.com/drk1wi/portspoof/blob/master/system_files/iptables-config) and the [init script](https://github.com/drk1wi/portspoof/blob/master/system_files/init.d/portspoof.sh) bind the prerouting to `eth0` when you try it on `127.0.0.1` that would use the `lo` interface instead so the prerouting rules are not applied, no?

**Comment by Belval** [comment]
Issue was indeed with the interface.

Thank you.

**Comment by alasdairdc** [comment]
No problem.
